In [1]:
import numpy as np


In [2]:
#arrayinitialization
arr=np.array([2,3,4])
arr
print(arr.shape)


(3,)


In [3]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [4]:
arr=np.array([2,3,4])
arr.shape


(3,)

In [5]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b.shape

(2, 3)

In [6]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [7]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [9]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [10]:
#maximum
arr=np.array([2,3,4])
print(np.amax(arr))
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(np.amax(b))



4
6.0


In [11]:
#minimum
arr=np.array([2,3,4])
print(np.amin(arr))
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(np.amin(b))

2
1.5


In [12]:
#mean
arr=np.array([2,3,4])
print(np.mean(arr))
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(np.mean(b))

3.0
3.5833333333333335


In [13]:
#median
arr=np.array([2,3,4])
print(np.median(arr))
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(np.median(b))

3.0
3.5


In [14]:
#average
arr=np.array([2,3,4])
print(np.average(arr))
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(np.average(b))

3.0
3.5833333333333335


In [15]:
#standard deviation
arr=np.array([2,3,4])
print(np.std(arr))
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(np.std(b))

0.816496580927726
1.5920810978785667


In [16]:
#variance
arr=np.array([2,3,4])
print(np.var(arr))
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(np.var(b))


0.6666666666666666
2.534722222222222


In [18]:
#2darray
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [17]:
#3darray
c = np.arange(24).reshape(2, 3, 4)  
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [19]:
#ptp
arr=np.array([2,3,4])
print(np.ptp(arr))
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(np.ptp(b))

2
4.5
